/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SnippetsRouteImport } from './routes/snippets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsIndexRouteImport } from './routes/snippets/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as CommentsIndexRouteImport } from './routes/comments/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as SnippetsNewRouteImport } from './routes/snippets/new'
import { Route as SnippetsSnippetIdRouteImport } from './routes/snippets/$snippetId'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as PostsNewRouteImport } from './routes/posts/new'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CommentsRepliesRouteImport } from './routes/comments/replies'
import { Route as CommentsCommentIdRouteImport } from './routes/comments/$commentId'
import { Route as CategoriesCategoriesIdRouteImport } from './routes/categories/$categoriesId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAuthTypeRouteImport } from './routes/auth/$authType'
import { Route as SnippetsSnippetIdEditorRouteImport } from './routes/snippets/$snippetId/editor'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsRoute = SnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SnippetsRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIndexRoute = CommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsNewRoute = SnippetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SnippetsRoute,
} as any)
const SnippetsSnippetIdRoute = SnippetsSnippetIdRouteImport.update({
  id: '/$snippetId',
  path: '/$snippetId',
  getParentRoute: () => SnippetsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRepliesRoute = CommentsRepliesRouteImport.update({
  id: '/comments/replies',
  path: '/comments/replies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsCommentIdRoute = CommentsCommentIdRouteImport.update({
  id: '/comments/$commentId',
  path: '/comments/$commentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoriesIdRoute = CategoriesCategoriesIdRouteImport.update({
  id: '/categories/$categoriesId',
  path: '/categories/$categoriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthTypeRoute = AuthAuthTypeRouteImport.update({
  id: '/$authType',
  path: '/$authType',
  getParentRoute: () => AuthRoute,
} as any)
const SnippetsSnippetIdEditorRoute = SnippetsSnippetIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SnippetsSnippetIdRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/snippets': typeof SnippetsRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/$authType': typeof AuthAuthTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/categories/$categoriesId': typeof CategoriesCategoriesIdRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
  '/comments/replies': typeof CommentsRepliesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/snippets/$snippetId/editor': typeof SnippetsSnippetIdEditorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/$authType': typeof AuthAuthTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/categories/$categoriesId': typeof CategoriesCategoriesIdRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
  '/comments/replies': typeof CommentsRepliesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/snippets': typeof SnippetsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/snippets/$snippetId/editor': typeof SnippetsSnippetIdEditorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/snippets': typeof SnippetsRouteWithChildren
  '/terms': typeof TermsRoute
  '/auth/$authType': typeof AuthAuthTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/categories/$categoriesId': typeof CategoriesCategoriesIdRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
  '/comments/replies': typeof CommentsRepliesRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/new': typeof PostsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/comments/': typeof CommentsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/snippets/$snippetId/editor': typeof SnippetsSnippetIdEditorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/snippets'
    | '/terms'
    | '/auth/$authType'
    | '/auth/login'
    | '/auth/register'
    | '/categories/$categoriesId'
    | '/comments/$commentId'
    | '/comments/replies'
    | '/demo/tanstack-query'
    | '/posts/$postId'
    | '/posts/new'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/snippets/$snippetId'
    | '/snippets/new'
    | '/users/$userId'
    | '/categories'
    | '/comments'
    | '/posts'
    | '/snippets/'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/snippets/$snippetId/editor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/terms'
    | '/auth/$authType'
    | '/auth/login'
    | '/auth/register'
    | '/categories/$categoriesId'
    | '/comments/$commentId'
    | '/comments/replies'
    | '/demo/tanstack-query'
    | '/posts/$postId'
    | '/posts/new'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/snippets/$snippetId'
    | '/snippets/new'
    | '/users/$userId'
    | '/categories'
    | '/comments'
    | '/posts'
    | '/snippets'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/snippets/$snippetId/editor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/auth'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/snippets'
    | '/terms'
    | '/auth/$authType'
    | '/auth/login'
    | '/auth/register'
    | '/categories/$categoriesId'
    | '/comments/$commentId'
    | '/comments/replies'
    | '/demo/tanstack-query'
    | '/posts/$postId'
    | '/posts/new'
    | '/settings/account'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/snippets/$snippetId'
    | '/snippets/new'
    | '/users/$userId'
    | '/categories/'
    | '/comments/'
    | '/posts/'
    | '/snippets/'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/snippets/$snippetId/editor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SnippetsRoute: typeof SnippetsRouteWithChildren
  TermsRoute: typeof TermsRoute
  CategoriesCategoriesIdRoute: typeof CategoriesCategoriesIdRoute
  CommentsCommentIdRoute: typeof CommentsCommentIdRoute
  CommentsRepliesRoute: typeof CommentsRepliesRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsNewRoute: typeof PostsNewRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CommentsIndexRoute: typeof CommentsIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets': {
      id: '/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/'
      fullPath: '/snippets/'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof SnippetsRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/': {
      id: '/comments/'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/new': {
      id: '/snippets/new'
      path: '/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof SnippetsNewRouteImport
      parentRoute: typeof SnippetsRoute
    }
    '/snippets/$snippetId': {
      id: '/snippets/$snippetId'
      path: '/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof SnippetsSnippetIdRouteImport
      parentRoute: typeof SnippetsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/replies': {
      id: '/comments/replies'
      path: '/comments/replies'
      fullPath: '/comments/replies'
      preLoaderRoute: typeof CommentsRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/$commentId': {
      id: '/comments/$commentId'
      path: '/comments/$commentId'
      fullPath: '/comments/$commentId'
      preLoaderRoute: typeof CommentsCommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoriesId': {
      id: '/categories/$categoriesId'
      path: '/categories/$categoriesId'
      fullPath: '/categories/$categoriesId'
      preLoaderRoute: typeof CategoriesCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/$authType': {
      id: '/auth/$authType'
      path: '/$authType'
      fullPath: '/auth/$authType'
      preLoaderRoute: typeof AuthAuthTypeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/snippets/$snippetId/editor': {
      id: '/snippets/$snippetId/editor'
      path: '/editor'
      fullPath: '/snippets/$snippetId/editor'
      preLoaderRoute: typeof SnippetsSnippetIdEditorRouteImport
      parentRoute: typeof SnippetsSnippetIdRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAuthTypeRoute: typeof AuthAuthTypeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthTypeRoute: AuthAuthTypeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SnippetsSnippetIdRouteChildren {
  SnippetsSnippetIdEditorRoute: typeof SnippetsSnippetIdEditorRoute
}

const SnippetsSnippetIdRouteChildren: SnippetsSnippetIdRouteChildren = {
  SnippetsSnippetIdEditorRoute: SnippetsSnippetIdEditorRoute,
}

const SnippetsSnippetIdRouteWithChildren =
  SnippetsSnippetIdRoute._addFileChildren(SnippetsSnippetIdRouteChildren)

interface SnippetsRouteChildren {
  SnippetsSnippetIdRoute: typeof SnippetsSnippetIdRouteWithChildren
  SnippetsNewRoute: typeof SnippetsNewRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
}

const SnippetsRouteChildren: SnippetsRouteChildren = {
  SnippetsSnippetIdRoute: SnippetsSnippetIdRouteWithChildren,
  SnippetsNewRoute: SnippetsNewRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
}

const SnippetsRouteWithChildren = SnippetsRoute._addFileChildren(
  SnippetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SnippetsRoute: SnippetsRouteWithChildren,
  TermsRoute: TermsRoute,
  CategoriesCategoriesIdRoute: CategoriesCategoriesIdRoute,
  CommentsCommentIdRoute: CommentsCommentIdRoute,
  CommentsRepliesRoute: CommentsRepliesRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsNewRoute: PostsNewRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CommentsIndexRoute: CommentsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
